### ISSUE TITLE
JDBC base URL must handle trailing slash ('/')

### ISSUE THREAD

**Issue by fpompermaier** [ververica/flink-sql-gateway#29]
Currently, when I add a JDBC catalog to the YAML file I need to add the last '/' to the url.

The following config works:

```
catalogs:
   - name: mypg
     type: jdbc
     default-database: postgres
     username: postgres
     password: mysecretpassword
     base-url: jdbc:postgresql://localhost:5432/
```

but this doesn't:

```
     base-url: jdbc:postgresql://localhost:5432
```
